# base image
image: "ruby:2.4.1"

# build stages
stages:
  - staging
  - production

    # cache gems in between builds
cache:
  paths:
    - vendor/ruby
    - node_modules

deploy_to_staging:
  stage: staging
  only:
    - develop
  before_script:
    - gem install bundler -v 1.13.7 --no-ri --no-rdoc
    - bundle install -j $(nproc) --path vendor
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  environment: staging
  script:
    - cap staging deploy

deploy_to_production:
  stage: production
  only:
    - master
  before_script:
    - gem install bundler -v 1.13.7 --no-ri --no-rdoc
    - bundle install -j $(nproc) --path vendor
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  environment: production
  script:
    - cap production deploy
