version: "3.8"
services:
  web:
    build:
      dockerfile: Dockerfile.development
    ports: ["3000:3000"]
    environment:
      DATABASE_URL: postgres://postgres:password@db/postgres
    volumes:
      - .:/usr/local/src/app
      - /usr/local/src/app/node_modules
    depends_on:
      - db
  db:
    image: postgres:9.6-alpine3.15
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
